# Generated by Django 4.2.7 on 2023-11-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybankingapp', '0004_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybankingapp.district'),
        ),
    ]
