# Generated by Django 4.2.7 on 2023-11-24 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybankingapp', '0005_alter_userprofile_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='distric',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mybankingapp.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(max_length=50),
        ),
    ]
