# Generated by Django 4.2.7 on 2023-11-24 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybankingapp', '0006_rename_name_district_distric_remove_branch_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='distric',
            new_name='name',
        ),
    ]
