# Generated by Django 4.2.7 on 2023-11-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybankingapp', '0007_rename_branch_branch_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='district',
            new_name='branch',
        ),
    ]
