# Generated by Django 4.2.7 on 2023-11-24 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybankingapp', '0008_rename_district_branch_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='name',
            new_name='district',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybankingapp.district'),
        ),
    ]
