# Generated by Django 4.2.7 on 2023-11-24 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybankingapp', '0009_rename_name_district_district_remove_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybankingapp.district'),
        ),
    ]
